volumes:
  pg_data:
    driver: local

x-base:
  &base-backend
  stdin_open: true
  tty: true
  env_file:
    - .env
  volumes:
    - .:/app

services:

  backend:
    <<: *base-backend
    build:
      context: .
    env_file:
      - .env
    command: gunicorn -c gunicorn-conf.py server:app --reload
    ports:
        - "4001:4000"