line-length = 120
exclude = [".venv", ".vscode", "__init__.py"]

[lint]
select = ["E", "W", "I", "F", "T20", "Q", "S", "N", "C4", "ERA"]
fixable = ["ALL"]
flake8-quotes = { docstring-quotes = "double", inline-quotes = "single", multiline-quotes = "double", avoid-escape = false }


[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
force-single-line = true
