repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
        files: user_manager/.*\.py$
      - id: end-of-file-fixer
        exclude: static|README.md|release_notes
        files: user_manager/.*\.py$
      - id: check-docstring-first
        files: user_manager/.*\.py$
      - id: debug-statements
        files: user_manager/.*\.py$
      - id: double-quote-string-fixer
        files: user_manager/.*\.py$
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: [ --line-length=120, -S ]
        files: user_manager/.*\.py$
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-typing-imports
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-spellcheck
          - dlint
          - darglint
          - mccabe
          - pep8-naming
          - flake8-isort
        args:
          - "--max-line-length=120"
          - "--classmethod-decorators=classmethod"
          - "--whitelist=UserManager/whitelist.txt"
          - "--config=UserManager/.flake8"
        files: user_manager/.*\.py$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: local
    hooks:
      - id: mypy
        name: Mypy check
        entry: sh -c 'mypy --config-file=UserManager/.mypy.ini UserManager/user_manager || exit 1'
        language: system
        pass_filenames: false
        files: user_manager/.*\.py$
      - id: bandit-security-check
        name: Bandit security check
        entry: bandit
        args: [ -q, -x, test ]
        exclude: settings/constants.py
        language: system
        files: user_manager/
