volumes:
  pg_data:
    driver: local

x-base:
  &base-backend
  stdin_open: true
  tty: true
  env_file:
    - .env
  depends_on:
    - db
  volumes:
    - .:/app

services:
  db:
    image: postgres:16
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: user_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    <<: *base-backend
    build:
      context: .
    command: gunicorn -k uvicorn.workers.UvicornWorker -c gunicorn-conf.py --timeout 60 server:app
    ports:
        - "4000:4000"