volumes:
  pg_data:
    driver: local

x-base:
  &base-backend
  stdin_open: true
  tty: true
  env_file:
    - .env
  volumes:
    - .:/app

services:

  backend:
    <<: *base-backend
    build:
      context: .
    command: gunicorn -k uvicorn.workers.UvicornWorker -c gunicorn-conf.py --timeout 60 server:app
    ports:
        - "4000:4000"