line-length = 120
exclude = [".venv", ".vscode", ".idea", "__init__.py", "user_manager/tests/**/*.py", "constants.py"]

[lint]
select = ["E", "W", "I", "F", "T20", "Q", "S", "N", "C4", "ERA"]
fixable = ["ALL"]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
force-single-line = true

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"
avoid-escape = false
